name: Publish Site with Timestamp
run-name: ${{ github.actor }} has updated the main branch, publishing site with timestamp
on:
  push:
    branches: main
    paths:
      - 'src/**'
      - wix.config.json
      - '!**.md'
      - .github/workflows/publish-timed.yml
      - .github/scripts/stamp.sh
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Wix CLI
        run: npm i -g @wix/cli
      - name: Login
        run: wix login --api-key ${{ secrets.WIX_CLI }}

      - name: Check out site source
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
            wix.config.json            
            .github

      - name: Mark timestamp
        run: >
          export RUN=${{ github.run_id }};
          ./.github/scripts/stamp.sh
          
      - name: Publish
        run: wix publish --source local -y
